apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxtest2
  namespace: flux-system
spec:
  interval: 1m
  path: "./configs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs2